name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print ShellCheck version
        run: shellcheck --version
      - name: Run ShellCheck
        run: |
          find . \
            -type d -name '.git' -prune \
            -o \
            -type f \( \
              -exec sh -c 'file --brief "$1" \
                | grep -qE "((Bourne-Again|POSIX) shell|/usr/bin/env sh) script"' _ {} \; \
              -o \
              -name '*.bash' -o -name '*.sh' \
            \) \
            -exec shellcheck --color=always {} +
